Mongo:
    Host: '127.0.0.1'
    DBName: 'Valor'
serverName: Valor
networkWebsite: valorhcf.net
statsRoot: valorhcf.net/stats
tab:
  serverName: '&4&lHCF'
  sectionColor: '&7'
  infoColor: '&c'
nightmare:
  enabled: true
  worldName: "NightmareEvent"
glowstoneMountain: false
cavern: false
startingTimer: false
forceInvites: true
squads: false
idleCheck: true
uhcHealing: false
passiveTag: true
allowBoosting: false
waterPlacementInClaims: false
blockRemoval: false
rodPrevention: false
skybridgePrevention: false
reduceArmorDamage: true
blockEntitiesThroughPortals: true
archerTagColor: YELLOW
defaultRelationColor: RED
pvpClasses:
  archer: true
  bard: true
  rogue: true
  ranger: true
minerWorld:
  regen:
    COAL_ORE: 30
    IRON_ORE: 60
    GOLD_ORE: 90
    DIAMOND_ORE: 120
potions:
  REGEN:
    splash: false
    drinkables: false
  SPEED:
    splash: true
    drinkables: true
  FIRE_RESISTANCE:
    splash: true
    drinkables: true
  POISON:
    splash: true
    drinkables: false
  INSTANT_HEAL:
    splash: true
    drinkables: true
  NIGHT_VISION:
    splash: true
    drinkables: true
  WEAKNESS:
    splash: false
    drinkables: false
  STRENGTH:
    splash: false
    drinkables: false
  SLOWNESS:
    splash: true
    drinkables: false
  INSTANT_DAMAGE:
    splash: false
    drinkables: false
  WATER_BREATHING:
    splash: true
    drinkables: true
  INVISIBILITY:
    splash: false
    drinkables: false
gems:
  STONE: 0.1
  COAL_ORE: 0.5
  IRON_ORE: 1.0
  GOLD_ORE: 2.0
  REDSTONE_ORE: 0.5
  LAPIS_ORE: 5.0
  DIAMOND_ORE: 5.0
  EMERALD_ORE: 15.0
reclaims:
  Test:
    priority: 1
    permission: 'reclaim.test'
    commands:
      - crate give to %player% Gay 16
      - pouch give %player% CRATEToken3 3
      - pouch give %player% CRATEMoney3 2
  Test2:
    priority: 1
    permission: 'reclaim.test2'
    commands:
      - crate give to %player% GAY 10