name: HCTeams
version: ${git.commit.id.abbrev}
author: ${minehq.pluginAuthor}
main: net.frozenorb.foxtrot.Foxtrot
depend: [ qLib, ProtocolLib, Hydrogen, CrazyEnchantments]
softdepend: [ LunarClient-API ]
